config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  get 'city/index'
  get 'city/show'
  get 'welcome/hello'
  get 'team/display'
  get 'contact/display'
  get 'home/display'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get 'city/show'
  get 'welcome/:id', to: 'welcome#hello'
  #get '/gossips/:gossip_id', to: 'gossips#display', as: 'my_gossip'
  #get '/users/:user_id', to: 'users#display', as: 'my_user'

  root 'home#display'
  get '/contact', to: 'contact#display'
  get '/team', to: 'team#display'

  resources  :gossips do
    resources   :comments
  end

  resources  :users
  resources   :city, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    validates :zipcode, presence: true, length: {maximum: 5}
    validates :name, presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :gossip_id, presence: true
  validates :content, presence: true
  validates :like, presence:true
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true, length: {minimum: 2, maximum: 14}
    validates :content, presence: true, length: {maximum: 300}
    validates :user_id, presence: true
    belongs_to :user
    has_many :comment
    has_many :links_tags
    has_many :tags, through: :links_tags
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, length: {maximum: 20}
    has_many :links_tags
    has_many :gossips, through: :links_tags
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true, length: {maximum: 140}
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :age, presence: true, length: {maximum: 3}
    validates :city_id, presence: true
    belongs_to :city
    has_many :gossips
    has_many :comment
    has_secure_password
    has_many :likes
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find_by(id: @user.city_id)
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
      # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
      @gossip = Gossip.new
  end

  def create
      # Méthode qui crée un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur

      @gossip = Gossip.new('title' => params[:title], 'content' => params[:content], 'city_id' => rand(City.all.first.id..City.all.last.id), 'user_id' => "5")
      # @gossip.user = current_user

      if @gossip.save
        flash[:success] = "Potin bien créé !"
        redirect_to root_path
      else
        render new_gossip_path
      end
  end

  def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      @gossip = Gossip.find(params[:id])
  end

  def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
        @gossip = Gossip.find(params[:id])
        @gossip.title = params[:title]
        @gossip.content = params[:content]
          if @gossip.update('title' => params[:gossip][:title], 'content' => params[:gossip][:content])
            redirect_to @gossip
          else
            render :edit
          end

  end

  def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to gossips_path

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def display
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def display
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @user = User.all
end

def show
  @user = User.find(params[:id])
end

def new
  @user = User.new
end

def create
  # Méthode qui crée un user à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur

  @user = User.new('first_name' => params[:first_name], 'last_name' => params[:last_name], 'email' => params[:email], 'password' => params[:password], 'city_id' => rand(City.all.first.id..City.all.last.id), 'description' => params[:description], 'age' => params[:age])
  if @user.save
    redirect_to @user
  else
    render :new
  end
end

def edit
  @user = user.find(params[:id])
end

def update
end

def destroy
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
 end

  def log_in(user)
   session[:user_id] = user.id
 end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<div class="container">
  <div class="form-group row">
    <div class="col-10">

      <h2>Modifie ton dernier potin</h2><br>

      <%= form_for @gossip do |f| %>

        <p>Auteur: <%= User.find(@gossip.user_id).first_name%></p><br>

        <%= f.label 'Le Titre' %><br>
        <%= f.text_field :title, class: 'form-control' %><br><br />

        <%= f.label 'Le Contenu' %><br>
        <%= f.text_area :content, class: 'form-control'  %><br><br />

        <%= f.submit "Submit Article", class: 'btn btn-success' %>
      <% end %>

      <!-- affiche les erreurs qui empêchent la modification du potin -->
      <% if @gossip.errors.any? %>
        <div class="alert alert-warning mt-2" role="alert">
          <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
          <ul>
            <% @gossip.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <p>Merci de réessayer</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="container">
    <div class="row mx-auto">
      <div class="col-10">
        <p>💁 Voici la liste des potins :</p>
      </div>
      </div>
  
      <div class="row">
      <% Gossip.all.each do |potin|%>
        <div class="col">
          <div class="card mb-3" style="width: 17rem; height: 12rem;">
            <div class="card-body">
              <h5 class="card-title"><%= potin.title.capitalize!%></h5>
              <h6 class="card-subtitle mb-2 text-muted">by <%= User.find_by(id: potin.user_id).first_name%> </h6>
              <p class="card-text"><%= potin.content[0..50] %>...</p> 
                <div class="col text-center">
                  <a href="<%= gossip_path(potin.id)%>" class="btn btn-info">Voir plus</a>
                </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>
</div>

app/views/gossips/new.html.erb
<div class="container">
  <div class="row">

    <div class="col text-center">
      <h2>Entre ton dernier potin</h2>
    </div>

    <div class="col-12">
        <div class="form-group">
          <%= form_tag url_for(action: 'create'), method: "post" do %>

            <%= label_tag 'Title' %>
            <%= text_field_tag 'title', @gossip.title, class: 'form-control' %>

            <br /> <br />
                
            <%= label_tag 'Content' %>
            <%= text_area_tag 'content', @gossip.content, class: 'form-control' %>

            <br /> <br />
                
            <%= submit_tag "Create Gossip", class: 'btn btn-success' %>
          <% end %>
        </div>


        <!-- affiche les erreurs qui empêchent la création du nouveau potin -->
        <% if @gossip.errors.any? %>
          <div class="alert alert-warning mt-2" role="alert">
            <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
              <ul>
                <% @gossip.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <p>Merci de réessayer</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gossips/show.html.erb
<div class="container show_gossip">
  <div class="col text-center">
    <h2>Voici le gossip n°<%=@gossip.id%></h2><br>
  </div>

  <div class="card mx-3">
    <div class="card-header">
      <strong><%= @gossip.title.capitalize!%></strong>
    </div>

    <div class="card-body px-4">

      <blockquote class="blockquote mb-0">
        <em>"<%= @gossip.content %>"</em><p></p>
        <footer class="blockquote-footer">
          <p>rédigé le <%= @gossip.created_at %></p>
          <p>Par : <a href="<%=user_path(@gossip.user_id)%>" class="card-link"><%= User.find(@gossip.user_id).first_name%> <%= User.find(@gossip.user_id).last_name %></a></p>
          <p>Clique <a href="<%=city_path(@gossip.city_id)%>" class="card-link">ici</a> pour voir tout les gossips de <%=City.find(@gossip.city_id).name%>.</p>

          <%if current_user%>
            <%if current_user.id == @gossip.user_id%>
              <div class="row flex-row">
                <a href="<%=edit_gossip_path(@gossip.id)%>" class="btn btn-info ml-4">Modifier</a>
                <%= form_tag url_for(action: 'destroy'), method: "delete" do%>
                  <%= submit_tag "Supprimer", class: 'btn btn-danger ml-3'%>
                <%end%>
              </div>
            <%end%>
          <%else%>
              <br><p>Connecte toi pour modifier tes potins</p>
          <%end%>
        </footer>
      </blockquote>
    </div>
  </div>
</div>