config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  get 'city/index'
  get 'city/show'
  get 'welcome/hello'
  get 'team/display'
  get 'contact/display'
  get 'home/display'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get 'city/show'
  get 'welcome/:id', to: 'welcome#hello'
  #get '/gossips/:gossip_id', to: 'gossips#display', as: 'my_gossip'
  #get '/users/:user_id', to: 'users#display', as: 'my_user'

  root 'home#display'
  get '/contact', to: 'contact#display'
  get '/team', to: 'team#display'

  resources  :gossips do
    resources   :comments
  end

  resources  :users
  resources   :city, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    validates :zipcode, presence: true, length: {maximum: 5}
    validates :name, presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :gossip_id, presence: true
  validates :content, presence: true
  validates :like, presence:true
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true, length: {minimum: 2, maximum: 14}
    validates :content, presence: true, length: {maximum: 300}
    validates :user_id, presence: true
    belongs_to :user
    has_many :comment
    has_many :links_tags
    has_many :tags, through: :links_tags
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, length: {maximum: 20}
    has_many :links_tags
    has_many :gossips, through: :links_tags
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true, length: {maximum: 140}
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :age, presence: true, length: {maximum: 3}
    validates :city_id, presence: true
    belongs_to :city
    has_many :gossips
    has_many :comment
    has_secure_password
    has_many :likes
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find_by(id: @user.city_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def display
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def display
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @user = User.all
end

def show
  @user = User.find(params[:id])
end

def new
  @user = User.new
end

def create
  # Méthode qui crée un user à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur

  @user = User.new('first_name' => params[:first_name], 'last_name' => params[:last_name], 'email' => params[:email], 'password' => params[:password], 'city_id' => rand(City.all.first.id..City.all.last.id), 'description' => params[:description], 'age' => params[:age])
  if @user.save
    redirect_to @user
  else
    render :new
  end
end

def edit
  @user = user.find(params[:id])
end

def update
end

def destroy
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
 end

  def log_in(user)
   session[:user_id] = user.id
 end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/display.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center pt-3">
      <%if current_user%>
        <h1>Bonjour <%=current_user.first_name%> !</h1><br>
      <%else%>
        <h1>Bonjour moussaillon</h1><br>
      <%end%>
    </div>
  </div>

  <div class="row">
    <div class="col text-center pb-2">
      <a href="<%= new_gossip_path%>" class="btn btn-success">Ajoute un gossip !</a>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-10">
        <p>💁 Voici la liste des potins :</p>
      </div>
    </div>

    <div class="row">
      <% Gossip.all.each do |potin|%>
        <%@gossip = potin %>
        <div class="col">
          <div class="card mb-4" style="width: 17rem; height: 12rem;">
            <div class="card-body">
              <h5 class="card-title"><%= potin.title.capitalize!%></h5>
              <h6 class="card-subtitle mb-2 text-muted">by <%= User.find_by(id: potin.user_id).first_name%> </h6>
              <p class="card-text"><%= @gossip.content[0..50] %>...</p>
                <div class="col text-center">
                  <a href="<%= gossip_path(@gossip.id)%>" class="btn btn-info">Voir plus</a>
                </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>
</div>

app/views/team/display.html.erb
<div class="container"
  <div class="row"
    <div class="col mx-5">
      <div class="alert alert-info" role="alert">
        <h4 class="alert-heading text-center">Salut toi!</h4>
        <p>Moi C'est Karim</p>
        <hr>
        <p class="mb-0">Je suis seul dans ma team et très content de t'accueillir sur mon site</p>
      </div>
    </div>
  </div>
</div>