config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  get 'city/index'
  get 'city/show'
  get 'welcome/hello'
  get 'team/display'
  get 'contact/display'
  get 'home/display'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get 'city/show'
  get 'welcome/:id', to: 'welcome#hello'
  #get '/gossips/:gossip_id', to: 'gossips#display', as: 'my_gossip'
  #get '/users/:user_id', to: 'users#display', as: 'my_user'

  root 'home#display'
  get '/contact', to: 'contact#display'
  get '/team', to: 'team#display'

  resources  :gossips do
    resources   :comments
  end

  resources  :users
  resources   :city, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

    validates :zipcode, presence: true, length: {maximum: 5}
    validates :name, presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :gossip_id, presence: true
  validates :content, presence: true
  validates :like, presence:true
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true, length: {minimum: 2, maximum: 14}
    validates :content, presence: true, length: {maximum: 300}
    validates :user_id, presence: true
    belongs_to :user
    has_many :comment
    has_many :links_tags
    has_many :tags, through: :links_tags
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, length: {maximum: 20}
    has_many :links_tags
    has_many :gossips, through: :links_tags
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true, length: {maximum: 140}
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :age, presence: true, length: {maximum: 3}
    validates :city_id, presence: true
    belongs_to :city
    has_many :gossips
    has_many :comment
    has_secure_password
    has_many :likes
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find_by(id: @user.city_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def display
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
 end

  def log_in(user)
   session[:user_id] = user.id
 end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="icon" type="image/png" sizes="16x16" href="https://www.thehackingproject.org/assets/favicon/favicon-16x16-d96ba65e5785d32474df9ebc6fbfd5442c751d527b10981a474bc3b7a4079d01.png">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand px-4" href="<%=root_path%>">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%=team_path%>">La Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=contact_path%>">Contact</a>
          </li>
          <%if !current_user%>
          <li class="nav-item">
            <a class="nav-link" href="<%=new_user_path%>">Inscription</a>
          </li>
          <li class="nav-item">
          </li>
            <a class="nav-link" href="<%=new_session_path%>">Connexion</a>
          <%else%>
          <li class="nav-item">
            <%= link_to "Deconnexion", session_path(session[:user_id]), :method => 'DELETE', class: "nav-link"%>
          </li>
          <%end%>
        </ul>
      </div>
    </nav>

    <section class="pt-3 mb-4">

      <%= yield %>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    </section>

    <footer class="footer">
      <div class="container text-center py-2">
        <p class="text-muted small">Ce site de potins vous est proposé par moi-même ☀</p>
      </div>
    </footer>

  </body>
</html>